#!/bin/bash

echo

#-----------------------
# build supporting code
#-----------------------

echo "Building font"
gcc -o utils/font utils/font.c -lm
echo

echo "Building pixels"
gcc -o utils/pixels utils/pixels.c -lm
echo

echo "Building locker"
gcc -o utils/locker utils/locker.c
echo



#--------------------------------
# convert raw image files to bin
#--------------------------------

echo "Converting images"
echo
utils/font		img/font.png				img/font.bin
utils/pixels		img/fontBonus.png				img/fontBonus.bin
utils/pixels		img/points.png				img/points.bin
utils/pixels		img/vegetables.png				img/vegetables.bin
utils/pixels		img/objects.png				img/objects.bin
utils/pixels		img/tiles.png				img/tiles.bin
utils/pixels		img/extra.png				img/extra.bin
utils/pixels		img/ladybug.png				img/ladybug.bin
utils/pixels		img/enemy1.png				img/enemy1.bin
utils/pixels		img/enemy2.png				img/enemy2.bin
utils/pixels		img/enemy3.png				img/enemy3.bin
utils/pixels		img/enemy4.png				img/enemy4.bin
utils/pixels		img/enemy5.png				img/enemy5.bin
utils/pixels		img/enemy6.png				img/enemy6.bin
utils/pixels		img/enemy7.png				img/enemy7.bin
utils/pixels		img/enemy8.png				img/enemy8.bin
utils/pixels		img/angel0.png				img/angel0.bin
utils/pixels		img/angel1.png				img/angel1.bin
utils/pixels		img/diamond.png				img/diamond.bin
echo

