#!/bin/bash

echo

#------------------------------------------------
# create build number from current date and time
#------------------------------------------------

echo
echo "$(date +%y.%j.%H%M)">output/projectBuild



#-----------------------------------------------
# setup pre-build stuff required by the project
#-----------------------------------------------

./buildPre



#---------------
# build project
#---------------

echo "Building project"
echo
if beebasm -title "$(<projectName)" -v -i asm/build.asm -do "$(<projectName).ssd" -opt 3 -dd -labels output/projectLabels>output/projectListing
then
echo



#------------------------------------------------
# setup post-build stuff required by the project
#------------------------------------------------

if ./buildPost
then
echo



#--------------------------------------------------
# update README.md with new build number
# --------------------------------------------------

echo "Updating README.md"
echo "**Build $(<output/projectBuild)**">../README.md.build
tail -n +2 ../README.md>>../README.md.build
rm ../README.md
mv ../README.md.build ../README.md
echo



#---------------------------------------
# display project name and build number
#---------------------------------------

echo "$(<projectName)" - Build "$(<output/projectBuild)"



#------------------
# run the project
#------------------

./run



#-----
# end
#-----

fi
fi
echo

