#!/bin/bash

echo

#--------------------------------------------------
# lock the dfs file names
#--------------------------------------------------

echo "Locking files in $(<projectName.txt).ssd"
echo
if ./utils/locker "./$(<projectName.txt).ssd" "!Boot  $" "CheckFs$" "Menu   $" "_Bonus $" "_Config$" "_Maps  $" "_Map1  $" "_Map2  $" "_Map3  $" "Loader $" "LadyBug$" "Reset  $" "_Reset $" "Editor $" "Cls    $" "EditorM$" "EditorT$" "ReadMe $"
then
echo
exit 0
else
exit 1
fi

