#!/bin/bash
xed 'projectListing.txt' 'asm/ladybug.asm' 'bas/boot.bas' 'asm/bonus.asm' 'asm/variables.asm' 'asm/constants.asm' 'asm/config.asm' 'bas/reset.bas' 'asm/!boot.asm' 'asm/loader.asm' 'asm/relocator.asm' 'asm/soundtables.asm' 'asm/editor.asm' 'bas/editor.bas' 'asm/mapnames.asm' 'asm/cls.asm' 'txt/readme.txt' 'asm/build.asm' 'asm/buildPre.asm' 'asm/buildPost.asm'

