#!/bin/bash
xed 'projectListing.txt' 'asm/ladybug.asm' 'bas/menu.bas' 'asm/bonus.asm' 'asm/variables.asm' 'asm/constants.asm' 'asm/config.asm' 'bas/reset.bas' 'asm/!boot.asm' 'bas/checkFs.bas' 'asm/loader.asm' 'asm/relocate.asm' 'asm/soundTables.asm' 'asm/editor.asm' 'bas/editor.bas' 'asm/mapNames.asm' 'asm/cls.asm' 'txt/readMe.txt' 'asm/build.asm' 'asm/memoryUsage.asm'

