#!/bin/bash

#----------------------------------------------------------------------
# read project name and create build number from current date and time
#----------------------------------------------------------------------

echo
bbcProjectName=$(<./projectName.txt)
bbcProjectBuild=$(date +%Y%m%d%H%M)
echo $bbcProjectBuild>./buildNumber.txt

#-------------------
# build extra stuff
#-------------------

./build-extra



#---------------
# build project
#---------------

echo "Building project"
echo
if beebasm -title "$bbcProjectName" -v -i build.asm -do "$bbcProjectName.ssd" -opt 3 -dd -labels labels.txt>./listing.txt
then
echo



#--------------------------------------------------
# lock the dfs file names
#--------------------------------------------------

echo "Locking files in $bbcProjectName.ssd"
echo
if ./utils/filelocker "$bbcProjectName.ssd" "!Boot  $" "Boot   $" "_Bonus $" "_Conf  $" "_Maps  $" "_Map1  $" "_Map2  $" "_Map3  $" "Loader $" "LadyBug$" "Reset  $" "_ConfR $" "Editor $" "Cls    $" "EditorM$" "EditorT$" "ReadMe $"
then
echo



#--------------------------------------------------
# update README.md with new build number
# --------------------------------------------------

echo "Updating README.md"
printf '**Build - %s**\n' "$bbcProjectBuild">../README.build.md
tail -n +2 ../README.md>>../README.build.md
rm ../README.md
mv ../README.build.md ../README.md
echo



#---------------------------------------
# display project name and build number
#---------------------------------------

printf '%s - Build %s\n' "$bbcProjectName" "$bbcProjectBuild"



#------------------
# run the project
#------------------

./run



#-----
# end
#-----

fi

fi
echo

