#!/bin/bash

echo

#-------------------
# compile utilities
#-------------------

echo "Building fontmaker"
gcc -o ./utils/fontmaker ./fontmaker/fontmaker.c
echo

echo "Building pixels"
gcc -o ./utils/pixels ./pixels/pixels.c
echo

echo "Building filelocker"
gcc -o ./utils/filelocker ./filelocker/filelocker.c
echo

#--------------------------------
# convert raw image files to bin
#--------------------------------

echo "Converting images"
echo
./utils/fontmaker	img-font.raw					img-font.bin
./utils/pixels		img-font-vegetable.raw		4	8	img-font-vegetable.bin
./utils/pixels		img-points.raw			10	10	img-points.bin
./utils/pixels		img-vegetables.raw		10	10	img-vegetables.bin
./utils/pixels		img-objects.raw			8	8	img-objects.bin
./utils/pixels		img-tiles.raw			6	8	img-tiles.bin
./utils/pixels		img-extra.raw			6	8	img-extra.bin
./utils/pixels		img-ladybug.raw			10	14	img-ladybug.bin
./utils/pixels		img-enemy1.raw			10	14	img-enemy1.bin
./utils/pixels		img-enemy2.raw			10	14	img-enemy2.bin
./utils/pixels		img-enemy3.raw			10	14	img-enemy3.bin
./utils/pixels		img-enemy4.raw			10	14	img-enemy4.bin
./utils/pixels		img-enemy5.raw			10	14	img-enemy5.bin
./utils/pixels		img-enemy6.raw			10	14	img-enemy6.bin
./utils/pixels		img-enemy7.raw			10	14	img-enemy7.bin
./utils/pixels		img-enemy8.raw			10	14	img-enemy8.bin
./utils/pixels		img-angel0.raw			10	14	img-angel0.bin
./utils/pixels		img-angel1.raw			10	14	img-angel1.bin
./utils/pixels		img-diamond.raw			8	6	img-diamond.bin
echo

