#!/bin/bash
xed 'listing.txt' 'ladybug.asm' 'boot.bas' 'bonus.asm' 'variables.asm' 'constants.asm' 'config.asm' 'reset.bas' '!boot.asm' 'loader.asm' 'relocator.asm' 'soundtables.asm' 'editor.asm' 'editor.bas' 'mapnames.asm' 'cls.asm' 'readme.txt' 'build.asm'

