#!/bin/bash

#-------------------
# read project name
#-------------------

bbcProjectName=$(<./projectName.txt)



#-----------------
# run the project
#-----------------

b-em -fullscreen -autoboot -disc "$bbcProjectName.ssd"

